### ISSUE TITLE
doesn't compile on ruby 2.0

### ISSUE THREAD

**Issue by minad** [brianmario/bzip2-ruby#19]
bzip2.c:6:21: fatal error: version.h: No such file or directory

**Comment by koraktor** [comment]
This should be fixed with 46939f3521eed0f12157c3a20a1a077cf51d17d1.

**Comment by maasha** [comment]
I have the same issue. Was the fix pushed ahead so it works with `gem install bzip2-ruby`?

**Comment by dsturnbull** [comment]
https://rubygems.org/gems/bzip2-ruby-rb20 as a temporary measure.

**Comment by dunric** [comment]
I'd add with Ruby 2.1.0 (the current stable) even _bzip2-ruby-rb20_ fails to compile:

```
Fetching: bzip2-ruby-rb20-0.2.7.gem (100%)
Building native extensions.  This could take a while...
ERROR:  Error installing bzip2-ruby-rb20:
        ERROR: Failed to build gem native extension.

    /usr/bin/ruby extconf.rb
checking for bzlib.h... yes
checking for BZ2_bzWriteOpen() in -lbz2... yes
creating Makefile

make "DESTDIR=" clean

make "DESTDIR="
compiling reader.c
reader.c: In function ‘bz_next_available’:
reader.c:55:18: warning: operation on ‘bzf->buf’ may be undefined [-Wsequence-point]
         bzf->buf = REALLOC_N(bzf->buf, char, bzf->buflen+BZ_RB_BLOCKSIZE+1);
                  ^
reader.c: In function ‘bz_reader_ungetc’:
reader.c:387:18: warning: operation on ‘bzf->buf’ may be undefined [-Wsequence-point]
         bzf->buf = REALLOC_N(bzf->buf, char, bzf->buflen + 2);
                  ^
reader.c: In function ‘bz_reader_ungets’:
reader.c:431:18: warning: operation on ‘bzf->buf’ may be undefined [-Wsequence-point]
         bzf->buf = REALLOC_N(bzf->buf, char, bzf->buflen + RSTRING_LEN(a) + 1);
                  ^
compiling common.c
compiling writer.c
writer.c: In function ‘bz_writer_close’:
writer.c:166:18: error: assignment of read-only member ‘klass’
         RBASIC(res)->klass = rb_cString;
                  ^
make: *** [writer.o] Error 1

make failed, exit code 2
```

GCC 4.8.2

**Comment by tosik** [comment]
me too
:+1:

**Comment by chewi** [comment]
This is broken for the same reason it was previously broken on Rubinius. The maintainer of Rubinius, @brixen, said the code was unnecessary anyway so I just removed it altogether. I also re-re-reverted the memory fix that has caused me double free segfaults. ;) Check out my fork at [chewi/bzip2-ruby](https://github.com/chewi/bzip2-ruby).

**Comment by minad** [comment]
@chewi Could this please be fixed in the official gem?

**Comment by chewi** [comment]
It's not my gem. @brianmario is reluctant to apply more fixes because the library is a big hacky mess. I understand his position and I would switch to rbzip2 but it lacks functionality I need. It is probably a suitable replacement for most people though.

**Comment by minad** [comment]
Then the question is if you would want to take over as maintainer? rbzip2 doesn't provide a string compression, but otherwise it seems to be a good alternative.

**Comment by IsraelBuitronD** [comment]
It does not compile too.
I use ruby (mri) `2.1.0`.

```
Fetching gem metadata from http://gemcutter.org/.........
Fetching gem metadata from http://rubygems.org/.........
Fetching additional metadata from http://gemcutter.org/..
Fetching additional metadata from http://rubygems.org/..
Resolving dependencies...

Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    /Users/foo/.rvm/rubies/ruby-2.1.0/bin/ruby extconf.rb 
checking for bzlib.h... yes
checking for BZ2_bzWriteOpen() in -lbz2... yes
creating Makefile

make "DESTDIR=" clean

make "DESTDIR="
compiling bzip2.c
bzip2.c:16:33: warning: unused parameter 'data' [-Wunused-parameter]
void bz_internal_finalize(VALUE data) {
                                ^
bzip2.c:55:25: warning: unused parameter 'self' [-Wunused-parameter]
VALUE bz_compress(VALUE self, VALUE str) {
                        ^
bzip2.c:123:27: warning: unused parameter 'self' [-Wunused-parameter]
VALUE bz_uncompress(VALUE self, VALUE data) {
                          ^
3 warnings generated.
compiling common.c
common.c:11:24: warning: unused parameter 'opaque' [-Wunused-parameter]
void * bz_malloc(void *opaque, int m, int n) {
                       ^
common.c:15:20: warning: unused parameter 'opaque' [-Wunused-parameter]
void bz_free(void *opaque, void *p) {
                   ^
2 warnings generated.
compiling reader.c
compiling writer.c
writer.c:35:27: warning: unused parameter 'obj' [-Wunused-parameter]
VALUE bz_str_closed(VALUE obj) {
                          ^
writer.c:166:28: error: read-only variable is not assignable
        RBASIC(res)->klass = rb_cString;
        ~~~~~~~~~~~~~~~~~~ ^
1 warning and 1 error generated.
make: *** [writer.o] Error 1

make failed, exit code 2

Gem files will remain installed in /Users/foo/.rvm/gems/ruby-2.1.0@worm_path_finder/gems/bzip2-ruby-rb20-0.2.7 for inspection.
Results logged to /Users/foo/.rvm/gems/ruby-2.1.0@worm_path_finder/extensions/x86_64-darwin-13/2.1.0/bzip2-ruby-rb20-0.2.7/gem_make.out
An error occurred while installing bzip2-ruby-rb20 (0.2.7), and Bundler cannot continue.
Make sure that `gem install bzip2-ruby-rb20 -v '0.2.7'` succeeds before bundling.
```

**Comment by chewi** [comment]
@neoriddle [Use my fork](https://github.com/chewi/bzip2-ruby).

**Comment by IsraelBuitronD** [comment]
@chewi Thank you very much. I works pretty good.

**Comment by bmedici** [comment]
The same issue with ruby 2.1.5, and none of the forks compiles...
